# Generated by Django 4.2.30 on 2026-05-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("skin", "Skincare"),
                            ("hair", "Haircare"),
                            ("makeup", "Makeup"),
                            ("wellness", "Wellness"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "problem",
                    models.CharField(
                        choices=[
                            ("hairfall", "Hair Fall"),
                            ("dandruff", "Dandruff"),
                            ("dryness", "Dryness"),
                            ("frizz", "Frizz"),
                            ("acne", "Acne"),
                            ("drak_circles", "Dark Circles"),
                            ("oily_skin", "Oily Skin"),
                            ("pigmentation", "Pigmentation"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=200,
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("price", models.CharField(max_length=20)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
                ),
                ("description", models.TextField()),
                ("how_to_use", models.TextField()),
                ("key_benefits", models.TextField(help_text="One Benefit Per Line ")),
                ("avoid_if", models.CharField(blank=True, max_length=200)),
                ("in_stock", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chat",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
