# Generated by Django 4.2.30 on 2026-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_alter_chat_id_alter_chat_session_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="products_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Product cards shown with this assistant message — saved for history replay.",
            ),
        ),
    ]
