# Generated by Django 4.2.30 on 2026-05-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_messages_products_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messages",
            name="products_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Product cards shown with this assistant message.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="problem",
            field=models.CharField(
                choices=[
                    ("prewash", "PH Balancer Prewash Shampoo"),
                    ("silkbond", "Silk Bond Treatment"),
                    ("shampoo", "Argan Shampoo"),
                    ("hairmask", "Argan Hair Mask"),
                    ("hairserum", "Argan Oil Hair Serum"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
