# Generated by Django 4.2.30 on 2026-05-14 06:38

import chatbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_alter_chat_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.CharField(
                default=chatbot.models.generate_uuid,
                editable=False,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="session_key",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="messages",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("skin", "Skincare"),
                    ("hair", "Haircare"),
                    ("makeup", "Makeup"),
                    ("wellness", "Wellness"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="key_benefits",
            field=models.TextField(blank=True, help_text="One benefit per line"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="problem",
            field=models.CharField(
                choices=[
                    ("hairfall", "Hair Fall"),
                    ("dandruff", "Dandruff"),
                    ("dryness", "Dryness"),
                    ("frizz", "Frizz"),
                    ("acne", "Acne"),
                    ("dark_circles", "Dark Circles"),
                    ("oily_skin", "Oily Skin"),
                    ("pigmentation", "Pigmentation"),
                    ("general", "General"),
                ],
                default="general",
                max_length=30,
            ),
        ),
    ]
